### ISSUE TITLE
Workaround for invalid yaml

### ISSUE THREAD

**Issue by mpapenbr** [mpapenbr/goirsdk#6]
The yaml available in the telemetry data may be invalid in certain situations.

It was spotted on the Fuji 8h race with the following team name

```
WeekendInfo:
 SeriesID: 546
 SeasonID: 4549
 SessionID: 221316997
 SubSessionID: 64852415
Drivers:
 - CarIdx: 33
   TeamID: 333206
   TeamName: @SimplyMod_F1 Racing Team
   CarNumber: "16"

```

Yaml strings may not start with the `@` character (see https://yaml.org/spec/1.2.2/ Example 5.9 Directive Indicator)

Until this is fixed by iRacing it would be best to pre process the yaml and put all team names in double-quotes `"`
